apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::631186618481:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-DeUNu61CwP6e
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
      userarn: arn:aws:iam::631186618481:user/bharath
      username: bharath
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-03T10:33:40Z"
  name: aws-auth
  namespace: kube-system
  uid: 41283815-8ae8-4fda-9d55-559859fe9783
